version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CLOUDYSKY-WEB-OPENSEARCH-API"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ov5r979w7jek"
s3_prefix = "CLOUDYSKY-WEB-OPENSEARCH-API"
region = "us-east-1"
profile = "san-dev"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
